package com.excellentcalendar.cloud.platform.api;

import com.excellentcalendar.cloud.platform.observability.RequestIdFilter;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

/**
 * Read-only access to the request ID generated by {@link RequestIdFilter}.
 */
public final class RequestContext {

    private RequestContext() {
    }

    public static String requestId() {
        if (RequestContextHolder.getRequestAttributes() instanceof ServletRequestAttributes attributes) {
            Object value = attributes.getRequest().getAttribute(RequestIdFilter.REQUEST_ID_ATTRIBUTE);
            if (value instanceof String requestId) {
                return requestId;
            }
        }
        return "unknown";
    }
}
